server:
  port: 9080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: user
    password: password
    driverClassName: org.postgresql.Driver