server:
  port: 9080


spring:
  application:
    name: customer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/customer?createDatabaseIfNotExist=true
    username: user
    password: password
    driverClassName: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka