server:
  port: 9081

spring:
  application:
    name: fraud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud?createDatabaseIfNotExist=true
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
